# Generated by Django 3.0.3 on 2020-02-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='accounted',
        ),
    ]
