# Generated by Django 3.1.7 on 2021-04-04 15:35

from django.db import migrations
import django.utils.timezone
import kamailio.models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='date',
            field=kamailio.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
