# Generated by Django 3.0.3 on 2020-02-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='ha1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='ha1b',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
