# Generated by Django 3.0.3 on 2020-03-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='callid',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='dst_domain',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='dst_ouser',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='dst_user',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='from_tag',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='method',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='sip_code',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='sip_reason',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='src_domain',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='src_ip',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='src_user',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='to_tag',
        ),
    ]
