# Generated by Django 3.1.7 on 2021-04-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0002_apiusage_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='serviceProvided',
            field=models.CharField(blank=True, choices=[('GENVZ', 'GENVZ'), ('USCALL', 'US')], default='USCALL', max_length=10, null=True),
        ),
    ]
