# Generated by Django 3.0.3 on 2020-02-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0002_auto_20200225_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={},
        ),
    ]
