# Generated by Django 3.0.3 on 2020-02-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0002_remove_acc_accounted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
