# Generated by Django 3.0.3 on 2020-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0002_auto_20200217_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='domain',
            field=models.CharField(max_length=64),
        ),
    ]
