# Generated by Django 3.1.7 on 2021-04-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0002_recarga_date'),
        ('kamailio', '0003_auto_20210402_2214'),
    ]

    operations = [
    ]
