# Generated by Django 3.0.3 on 2020-02-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0003_auto_20200225_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={'managed': False},
        ),
    ]
