# Generated by Django 3.1.7 on 2021-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0004_merge_20210404_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='cost',
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='serviceProvided',
            field=models.CharField(blank=True, choices=[('GENVZ', 'GENVZ'), ('USCALL', 'US')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='recarga',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
