# Generated by Django 3.0.3 on 2020-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0004_auto_20200331_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='callid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='dst_domain',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='dst_ouser',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='dst_user',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='endTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='from_tag',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='method',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='sip_code',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='sip_reason',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='src_domain',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='src_ip',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='src_user',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='startTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='to_tag',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
