# Generated by Django 3.1.7 on 2021-04-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0005_auto_20210404_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='recarga',
            name='amount',
            field=models.DecimalField(decimal_places=7, max_digits=11),
        ),
    ]
