# Generated by Django 3.0.3 on 2020-02-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0006_auto_20200225_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={},
        ),
    ]
