# Generated by Django 3.0.3 on 2020-02-25 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0007_auto_20200225_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='activewatchers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='aliases',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carrierfailureroute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carriername',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carrierroute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cpl',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dbaliases',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dialogvars',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dialplan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dispatcher',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='domainattrs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='domainname',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='domainpolicy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drgateways',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drgroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drgwlists',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drrules',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalblacklist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='htable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imcmembers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imcrooms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lcrgw',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lcrrule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lcrruletarget',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locationattrs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='missedcalls',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mohqcalls',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mohqueues',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mtree',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mtrees',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pdt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plpipes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='presentity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pua',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='purplemap',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='regrp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rlspresentity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rlswatchers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rtpengine',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rtpproxy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scasubscriptions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='silo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='siptrace',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='speeddial',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='toposd',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topost',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='trusted',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uacreg',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uidcredentials',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uiddomain',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uiddomainattrs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uidglobalattrs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uiduri',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uiduriattrs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uiduserattrs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uri',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userblacklist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usrpreferences',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='watchers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='xcap',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='acc',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
