# Generated by Django 3.0.3 on 2020-02-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamailio', '0008_auto_20200225_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activewatchers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='aliases',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carrierfailureroute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carriername',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carrierroute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cpl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dbaliases',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dialogvars',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dialplan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dispatcher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domainattrs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domainname',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domainpolicy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='drgateways',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='drgroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='drgwlists',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='drrules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='globalblacklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grp',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='htable',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imcmembers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imcrooms',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lcrgw',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lcrrule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lcrruletarget',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='locationattrs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='missedcalls',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mohqcalls',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mohqueues',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mtree',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mtrees',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pdt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='plpipes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='presentity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pua',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purplemap',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='regrp',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rlspresentity',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rlswatchers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rtpengine',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rtpproxy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scasubscriptions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='silo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='siptrace',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='speeddial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='toposd',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topost',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trusted',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uacreg',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uidcredentials',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uiddomain',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uiddomainattrs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uidglobalattrs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uiduri',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uiduriattrs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uiduserattrs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uri',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userblacklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usrpreferences',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='watchers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='xcap',
            options={'managed': False},
        ),
    ]
